[dependencies]
color-eyre = {workspace = true}
parking_lot = {workspace = true}
pin-project-lite = {workspace = true}
tokio = {features = ["rt"], workspace = true}
tokio-util = {workspace = true}
tracing = {workspace = true}

[package]
edition = "2024"
name = "spawn"
version = "0.1.0"
