[package]
name = "jellyhaj-image"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
color-eyre.workspace = true
image.workspace = true
jellyfin = { version = "0.1.4", path = "../../jellyfin-rs" }
jellyhaj-widgets-core = { version = "0.1.0", path = "../core" }
parking_lot.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
rayon.workspace = true
sqlx.workspace = true
stats-data = { version = "0.1.0", path = "../../stats-data" }
tokio = { workspace = true, features = ["sync"] }
tracing.workspace = true
