[dependencies]
jellyfin = {path = "../../jellyfin-rs", version = "0.1.4"}
jellyhaj-widgets-core = {path = "../core", version = "0.1.0"}
stats-data = {path = "../../stats-data", version = "0.1.0"}
tokio = {features = ["sync"], workspace = true}
bytes.workspace = true
color-eyre.workspace = true
image.workspace = true
parking_lot.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
rayon.workspace = true
sqlx.workspace = true
tracing.workspace = true

[package]
edition = "2024"
name = "jellyhaj-image"
version = "0.1.0"
