[dependencies]
color-eyre = {workspace = true}
config = {path = "../config"}
either = {workspace = true}
image = {workspace = true}
jellyfin = {path = "../jellyfin-rs"}
keybinds = {path = "../keybinds"}
libmpv = {default-features = false, path = "../libmpv-rs"}
parking_lot = {workspace = true}
player-core = {path = "../player-core"}
ratatui = {workspace = true}
ratatui-image = {workspace = true}
sqlx = {workspace = true}
stats-data = {path = "../stats-data", version = "0.1.0"}
tokio = {workspace = true}
tracing = {workspace = true}

[package]
edition = "2024"
name = "jellyhaj-core"
version = "0.1.0"
