
login_file = "login.toml"

mpv_profile= "default"
hwdec = "auto-safe"
mpv_log_level = "info"
#mpv_config_file = "/absolute/path/to/mpv-config-file"

# if not set fallback to default keybinds
#keybinds_file = "path"

