#injected into every map as key that shows the maps keybinds
#including Esc is useful as prefix for commands while text input mode is active
help_prefixes = ["?", "esc"]

[fetch]
q = "quit"

[play_mpv]
q = "quit"
space = "pause"
enter = "pause"

[user_view]
template = ["ud", "q", "o"]
r = "reload"
left = "prev"
back-tab = "prev"
right = "next"
tab = "next"
enter = "play"
R = "refresh-item"

[home_screen]
template = ["m", "o"]
r = "reload"
enter = "play-open"
R = "refresh-item"

[item_list_details]
template = ["m", "o"]
enter = "play"
r = "reload"
R = "refresh-parent-item"
"C-R" = "refresh-current-item"

[login_info]
backspace = "delete"
enter = "submit"
up = "next"
tab = "next"
down = "prev"
back-tab = "prev"
q = "quit"

[error]
template = ["m"]
k = "kill"

[item_details]
template = ["ud", "q"]
p = "play"
enter = "play"
r = "reload"
R = "refresh-item"

[refresh_item]
up = "up"
down = "down"
tab = "down"
enter = "select"
space = "select"
q = "quit"
esc = "quit"

[template.q]
q = "quit"

[template.ud]
up = "up"
down = "down"

[template.lr]
left = "left"
right = "right"

[template.m]
template = ["q", "ud", "lr"]

[template.o]
o = "open"
p = "play"
O = {name = "open-", e = "open-episode", S = "open-season", s = "open-series"}
