
# General Info:
# This file maps key inputs to commands.
# You can even define key combinations.
# Instead of traditional keybinds where you have to press
# multiple keys simultaneously you combine them by pressing
# them sequentially (well there are limited modifiers so you
# might have to press a maximum of 2 keys simultaneously).
# An example of this can be seen in the template.o table.
# There are also templates (just add a template key like in
# user_view), they are defined under [template.<name>]

#injected into every map as key that shows the maps keybinds
#including Esc is useful as prefix for commands while text input mode is active
help_prefixes = ["?", "esc"]

[fetch]
q = "quit"

[play_mpv]
q = "quit"
space = "pause"
enter = "pause"

[user_view]
template = ["ud", "q", "o"]
r = "reload"
left = "prev"
back-tab = "prev"
right = "next"
tab = "next"
enter = "play"
R = "refresh-item"

[home_screen]
template = ["m", "o"]
r = "reload"
enter = "play-open"
R = "refresh-item"
s = {name="show-", s="show-stats", l="show-logs"}

[item_list_details]
template = ["m", "o"]
enter = "play"
r = "reload"
R = "refresh-parent-item"
"C-R" = "refresh-current-item"

[login_info]
backspace = "delete"
enter = "submit"
up = "next"
tab = "next"
down = "prev"
back-tab = "prev"
q = "quit"

[error]
template = ["m"]
k = "kill"
l = "show-logs"

[item_details]
template = ["ud", "q"]
p = "play"
enter = "play"
r = "reload"
R = "refresh-item"

[refresh_item]
up = "up"
down = "down"
tab = "down"
enter = "select"
space = "select"
q = "quit"
esc = "quit"

[unsupported_item]
q = "quit"

[stats]
q="quit"

[logger]
space="space"
up="messages-up"
down="messages-down"
left="left"
right="right"
"+"="plus"
"-"="minus"
h="hide"
f="focus"
C-up="target-up"
C-down="target-down"
esc = "escape"
q="quit"

[template.q]
q = "quit"

[template.ud]
up = "up"
down = "down"

[template.lr]
left = "left"
right = "right"

[template.m]
template = ["q", "ud", "lr"]

[template.o]
o = "open"
p = "play"
# sub maps have a name that is displayed in the keybind help / context view
# all other key value combinations are normal keybinds (and can even be another sub map or an template)
O = {name = "open-", e = "open-episode", S = "open-season", s = "open-series"}
