[dependencies]
jellyhaj-widgets-core = {path = "../core", version = "0.1.0"}
color-eyre.workspace = true
ratatui.workspace = true
tracing.workspace = true

[package]
edition = "2024"
name = "jellyhaj-item-list"
version = "0.1.0"
