[package]
name = "jellyhaj-item-list"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
jellyhaj-widgets-core = { version = "0.1.0", path = "../core" }
ratatui.workspace = true
tracing.workspace = true
