[package]
name = "jellyhaj-widgets-core"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
config = { version = "0.1.0", path = "../../config" }
futures-channel = { version = "0.3.31", features = ["sink"] }
futures-util = { workspace = true, features = ["sink"] }
parking_lot.workspace = true
pin-project-lite.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
spawn = { version = "0.1.0", path = "../../spawn" }
tokio-util.workspace = true
tracing.workspace = true
