[dependencies]
config = {path = "../../config", version = "0.1.0"}
futures-channel = {features = ["sink"], version = "0.3.31"}
futures-util = {features = ["sink"], workspace = true}
spawn = {path = "../../spawn", version = "0.1.0"}
color-eyre.workspace = true
parking_lot.workspace = true
pin-project-lite.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[package]
edition = "2024"
name = "jellyhaj-widgets-core"
version = "0.1.0"
