[dependencies]
color-eyre = {workspace = true}
jellyfin = {path = "../jellyfin-rs"}
player-core = {path = "../player-core"}
zbus = {workspace = true}
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

[package]
edition = "2024"
name = "player-mpris"
version = "0.1.0"
